import { IRepositoryModel } from '../src/Models/RepositoryModel'

export const testRepository: IRepositoryModel = {
    id: 1,
    node_id: "MDEwOlJlcG9zaXRvcnkxMjM0NTY=",
    name: "example-repo",
    full_name: "user/example-repo",
    private: false,
    owner: {
        login: "user",
        id: 1,
        node_id: "MDQ6VXNlcjc4OTA=",
        avatar_url: "https://avatars.githubusercontent.com/u/7890?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/user",
        html_url: "https://github.com/user",
        followers_url: "https://api.github.com/users/user/followers",
        following_url: "https://api.github.com/users/user/following{/other_user}",
        gists_url: "https://api.github.com/users/user/gists{/gist_id}",
        starred_url: "https://api.github.com/users/user/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/user/subscriptions",
        organizations_url: "https://api.github.com/users/user/orgs",
        repos_url: "https://api.github.com/users/user/repos",
        events_url: "https://api.github.com/users/user/events{/privacy}",
        received_events_url: "https://api.github.com/users/user/received_events",
        type: "User",
        site_admin: false
    },
    html_url: "https://github.com/user/example-repo",
    description: "This is an example repository.",
    fork: false,
    url: "https://api.github.com/repos/user/example-repo",
    forks_url: "https://api.github.com/repos/user/example-repo/forks",
    keys_url: "https://api.github.com/repos/user/example-repo/keys{/key_id}",
    collaborators_url: "https://api.github.com/repos/user/example-repo/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/user/example-repo/teams",
    hooks_url: "https://api.github.com/repos/user/example-repo/hooks",
    issue_events_url: "https://api.github.com/repos/user/example-repo/issues/events{/number}",
    events_url: "https://api.github.com/repos/user/example-repo/events",
    assignees_url: "https://api.github.com/repos/user/example-repo/assignees{/user}",
    branches_url: "https://api.github.com/repos/user/example-repo/branches{/branch}",
    tags_url: "https://api.github.com/repos/user/example-repo/tags",
    blobs_url: "https://api.github.com/repos/user/example-repo/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/user/example-repo/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/user/example-repo/git/refs{/ref}",
    trees_url: "https://api.github.com/repos/user/example-repo/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/user/example-repo/statuses/{sha}",
    languages_url: "https://api.github.com/repos/user/example-repo/languages",
    stargazers_url: "https://api.github.com/repos/user/example-repo/stargazers",
    contributors_url: "https://api.github.com/repos/user/example-repo/contributors",
    subscribers_url: "https://api.github.com/repos/user/example-repo/subscribers",
    subscription_url: "https://api.github.com/repos/user/example-repo/subscription",
    commits_url: "https://api.github.com/repos/user/example-repo/commits{/sha}",
    git_commits_url: "https://api.github.com/repos/user/example-repo/git/commits{/sha}",
    comments_url: "https://api.github.com/repos/user/example-repo/comments{/number}",
    issue_comment_url: "https://api.github.com/repos/user/example-repo/issues/comments{/number}",
    contents_url: "https://api.github.com/repos/user/example-repo/contents/{+path}",
    compare_url: "https://api.github.com/repos/user/example-repo/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/user/example-repo/merges",
    archive_url: "http://github.com/users/{owner}/example-repo/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/user/example-repo/downloads",
    issues_url: "https://api.github.com/repos/user/example-repo/issues{/number}",
    pulls_url: "https://api.github.com/repos/user/example-repo/pulls{/number}",
    milestones_url: "https://api.github.com/repos/user/example-repo/milestones{/number}",
    notifications_url: "https://api.github.com/repos/user/example-repo/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/user/example-repo/labels{/name}",
    releases_url: "https://api.github.com/repos/user/example-repo/releases{/id}",
    deployments_url: "https://api.github.com/repos/user/example-repo/deployments",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    git_url: "git@github.com:user/example-repo.git",
    ssh_url: "git@github.com:user/example-repo.git",
    clone_url: "https://github.com/user/example-repo.git",
    svn_url: "https://github.com/user/example-repo",
    homepage: null,
    size: 1234,
    stargazers_count: 100,
    watchers_count: 100,
    language: null,
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: false,
    has_pages: false,
    has_discussions: false,
    forks_count: 50,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 5,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: ["example", "repository", "test"],
    visibility: 'public',
    forks: 50,
    open_issues: 5,
    watchers: 100,
    default_branch: 'main',
    score: 1.0
};


export const newTestRep: IRepositoryModel = {
    id: 1,
    node_id: "MDEwOlJlcG9zaXRvcnkxMjM0NTY=",
    name: "example-repo",
    full_name: "user/example-repo",
    private: true,
    owner: {
        login: "newUser",
        id: 1,
        node_id: "MDQ6VXNlcjc4OTA=",
        avatar_url: "https://avatars.githubusercontent.com/u/7890?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/user",
        html_url: "https://github.com/user",
        followers_url: "https://api.github.com/users/user/followers",
        following_url: "https://api.github.com/users/user/following{/other_user}",
        gists_url: "https://api.github.com/users/user/gists{/gist_id}",
        starred_url: "https://api.github.com/users/user/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/user/subscriptions",
        organizations_url: "https://api.github.com/users/user/orgs",
        repos_url: "https://api.github.com/users/user/repos",
        events_url: "https://api.github.com/users/user/events{/privacy}",
        received_events_url: "https://api.github.com/users/user/received_events",
        type: "User",
        site_admin: false
    },
    html_url: "https://github.com/user/example-repo",
    description: "This is an example repository.",
    fork: false,
    url: "https://api.github.com/repos/user/example-repo",
    forks_url: "https://api.github.com/repos/user/example-repo/forks",
    keys_url: "https://api.github.com/repos/user/example-repo/keys{/key_id}",
    collaborators_url: "https://api.github.com/repos/user/example-repo/collaborators{/collaborator}",
    teams_url: "https://api.github.com/repos/user/example-repo/teams",
    hooks_url: "https://api.github.com/repos/user/example-repo/hooks",
    issue_events_url: "https://api.github.com/repos/user/example-repo/issues/events{/number}",
    events_url: "https://api.github.com/repos/user/example-repo/events",
    assignees_url: "https://api.github.com/repos/user/example-repo/assignees{/user}",
    branches_url: "https://api.github.com/repos/user/example-repo/branches{/branch}",
    tags_url: "https://api.github.com/repos/user/example-repo/tags",
    blobs_url: "https://api.github.com/repos/user/example-repo/git/blobs{/sha}",
    git_tags_url: "https://api.github.com/repos/user/example-repo/git/tags{/sha}",
    git_refs_url: "https://api.github.com/repos/user/example-repo/git/refs{/ref}",
    trees_url: "https://api.github.com/repos/user/example-repo/git/trees{/sha}",
    statuses_url: "https://api.github.com/repos/user/example-repo/statuses/{sha}",
    languages_url: "https://api.github.com/repos/user/example-repo/languages",
    stargazers_url: "https://api.github.com/repos/user/example-repo/stargazers",
    contributors_url: "https://api.github.com/repos/user/example-repo/contributors",
    subscribers_url: "https://api.github.com/repos/user/example-repo/subscribers",
    subscription_url: "https://api.github.com/repos/user/example-repo/subscription",
    commits_url: "https://api.github.com/repos/user/example-repo/commits{/sha}",
    git_commits_url: "https://api.github.com/repos/user/example-repo/git/commits{/sha}",
    comments_url: "https://api.github.com/repos/user/example-repo/comments{/number}",
    issue_comment_url: "https://api.github.com/repos/user/example-repo/issues/comments{/number}",
    contents_url: "https://api.github.com/repos/user/example-repo/contents/{+path}",
    compare_url: "https://api.github.com/repos/user/example-repo/compare/{base}...{head}",
    merges_url: "https://api.github.com/repos/user/example-repo/merges",
    archive_url: "http://github.com/users/{owner}/example-repo/{archive_format}{/ref}",
    downloads_url: "https://api.github.com/repos/user/example-repo/downloads",
    issues_url: "https://api.github.com/repos/user/example-repo/issues{/number}",
    pulls_url: "https://api.github.com/repos/user/example-repo/pulls{/number}",
    milestones_url: "https://api.github.com/repos/user/example-repo/milestones{/number}",
    notifications_url: "https://api.github.com/repos/user/example-repo/notifications{?since,all,participating}",
    labels_url: "https://api.github.com/repos/user/example-repo/labels{/name}",
    releases_url: "https://api.github.com/repos/user/example-repo/releases{/id}",
    deployments_url: "https://api.github.com/repos/user/example-repo/deployments",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    pushed_at: new Date().toISOString(),
    git_url: "git@github.com:user/example-repo.git",
    ssh_url: "git@github.com:user/example-repo.git",
    clone_url: "https://github.com/user/example-repo.git",
    svn_url: "https://github.com/user/example-repo",
    homepage: null,
    size: 1234,
    stargazers_count: 20,
    watchers_count: 100,
    language: null,
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: false,
    has_pages: false,
    has_discussions: false,
    forks_count: 10,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 5,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: ["example", "repository", "test"],
    visibility: 'public',
    forks: 50,
    open_issues: 5,
    watchers: 100,
    default_branch: 'main',
    score: 1.0
};